-   id: flutter-analyze
    name: Flutter Code Analyze
    entry: run_analyze
    language: script
    files: \.dart$

-   id: flutter-format
    name: Flutter Code Format
    entry: run_format
    language: script
    files: \.dart$

-   id: flutter-test
    name: Flutter Test
    entry: run_test
    language: script
    files: \.dart$